#ifndef ILP_CONFIG_H
#define ILP_CONFIG_H

#define PROJECT_VERSION_MAJOR "1"
#define PROJECT_VERSION_MINOR "0"
#define PROJECT_VERSION_PATCH "0"
#define PROJECT_VERSION "1.0.0"

#endif // ILP_CONFIG_H
